### ISSUE TITLE
Falco, Rock Me Amadeus 

### ISSUE THREAD

**Issue by blgblade** [andygruber/songseeker-hitster-playlists#12]
ist vlt ansichtssache, aber ich habe mal die 165 in der  Originalspielplaylist ausgetauscht zu einer Version die der radioedit vermutlich näher kommt, da das intro einfach sonst vieeeeel zu lang ist

165,Falco,Rock Me Amadeus,https://www.youtube.com/watch?v=zUaSZXedM9Y,6b1bc7a495754fd73062055d90cf36e5ed3f4b77f7967fef3a15df66ec046075,Falco - Rock Me Amadeus [High Quality],1985

sitze gerade an der deutschen guilty pleasures (aaaa0015), kann ich die Tage auch die csv zur Verfügung stellen :)
(fehlen nur noch einige (>200^^) youtube links und die jahre stimmen nicht immer)

Danke btw für das script :) 

edit: ich seh gerade du hattest schon angefangen mit guily pleasures, hier haste noch meine komplette liste, da musst du nicht selber die restlichen raussuchen :) 
https://github.com/blgblade/songseeker-hitster-playlists/blob/main/hitster-de-aaaa0015.csv

**Comment by andygruber** [comment]
sehr nice, hab erst grad gesehen, aber die letzten 80 links nehm ich gerne von dir.

Bei der Originalplaylist hab ich noch vieles anders gemacht. Die neuen sind da etwas besser (hoffe ich  :-) )
