### ISSUE TITLE
[Question] Getting Spotify URLs from Hitster URLs?

### ISSUE THREAD

**Issue by jbaiter** [andygruber/songseeker-hitster-playlists#24]
I'm trying to create a CSV file for a currently unsupported Hitster pack that I would then contribute.
Is there an automated way to get the Spotify URL/song identifier given a Hitster URL encoded in a QR Code? Or is this a purely manual process?

**Comment by jbaiter** [comment]
Did some reverse engineering of the Android app, it looks like while there is some code in the app to dynamically fetch the track info from a Firebase database, I haven't actually be able to trace any runtime calls to that code.
Instead, the whole database is loaded at startup from https://hitster.jumboplay.com/hitster-assets/gameset_database.json

For every Hitster SKU it contains the language, set name, and a list of all cards in the set, with the number and the spotify track identifier.

This should make it easier to create new lists as new sets come out, mapping the spotify id to a youtube id should be pretty straightforward in most cases using spotipy and ytmusicapi.

**Comment by andygruber** [comment]
@jbaiter thx for sharing the info
